"""add tab id to chunks

Revision ID: 9a7cae16f10e
Revises: f39c310b0956
Create Date: 2026-05-01 15:14:20.866667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7cae16f10e'
down_revision: Union[str, Sequence[str], None] = 'f39c310b0956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('tab_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'chunks', 'tabs', ['tab_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_column('chunks', 'tab_id')
    # ### end Alembic commands ###
