"""add upload_id to files table

Revision ID: aa0e07c04d2e
Revises: dadebc996f76
Create Date: 2026-04-20 01:13:29.629672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0e07c04d2e'
down_revision: Union[str, Sequence[str], None] = 'dadebc996f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabs', 'created_at',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('tabs', 'updated_at',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    
    op.add_column('files', sa.Column('upload_id', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('files', 'upload_id')
    
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tabs', 'updated_at',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tabs', 'created_at',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###