"""updated schema

Revision ID: c83569c7c65f
Revises: f679d1536602
Create Date: 2026-03-09 14:07:59.669554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83569c7c65f'
down_revision: Union[str, Sequence[str], None] = 'f679d1536602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint('uq_folder_name_per_location', 'folders', ['owner_id', 'parent_id', 'name'])
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_constraint('uq_folder_name_per_location', 'folders', type_='unique')
    op.drop_column('folders', 'parent_id')
    # ### end Alembic commands ###
