"""initial schema

Revision ID: ca9d24c27f9c
Revises: 
Create Date: 2026-03-12 07:36:02.852211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9d24c27f9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('files', sa.Column('mime_type', sa.String(length=255), nullable=False))
    op.add_column('files', sa.Column('created_at', sa.String(length=50), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.String(length=50), nullable=False))
    op.add_column('folders', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint('uq_folder_name_per_location', 'folders', ['owner_id', 'parent_id', 'name'])
    op.create_foreign_key(None, 'folders', 'folders', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_constraint('uq_folder_name_per_location', 'folders', type_='unique')
    op.drop_column('folders', 'parent_id')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'mime_type')
    op.drop_column('files', 'status')
    # ### end Alembic commands ###
