"""add_chunk_fields_to_files

Revision ID: f39c310b0956
Revises: 5526c2da807e
Create Date: 2026-04-25 03:28:36.595271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39c310b0956'
down_revision: Union[str, Sequence[str], None] = '5526c2da807e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_chunks',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('uploaded', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_id', 'chunk_index', name='uq_file_chunk')
    )
    
    # Use server_default so existing rows get a value
    op.add_column('files', sa.Column('total_chunks', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('uploaded_chunks', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('files', sa.Column('is_upload_complete', sa.Boolean(), nullable=False, server_default='false'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_upload_complete')
    op.drop_column('files', 'uploaded_chunks')
    op.drop_column('files', 'total_chunks')
    op.drop_table('upload_chunks')
    # ### end Alembic commands ###
